@php($prefix = $schedule ? 'edit-'.$schedule->id : 'new')
<div class="row g-3" data-schedule-fields>
    <div class="col-md-6"><label class="form-label">Schedule name</label><input class="form-control" name="name" required maxlength="100" value="{{ old('name',$schedule?->name) }}" placeholder="Daily production backup"></div>
    <div class="col-md-3"><label class="form-label">Backup type</label><select class="form-select" name="backup_type" required>@foreach(['database','files','full'] as $type)<option value="{{ $type }}" @selected(old('backup_type',$schedule?->backup_type ?? 'full')===$type)>{{ ucfirst($type) }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Run time</label><input class="form-control" type="time" name="run_at" required value="{{ old('run_at',$schedule ? substr($schedule->run_at,0,5) : '02:00') }}"></div>
    <div class="col-md-4"><label class="form-label">Frequency</label><select class="form-select" name="frequency" required>@foreach(['daily','weekly','monthly'] as $frequency)<option value="{{ $frequency }}" @selected(old('frequency',$schedule?->frequency ?? 'daily')===$frequency)>{{ ucfirst($frequency) }}</option>@endforeach</select></div>
    <div class="col-md-4" data-weekly><label class="form-label">Day of week</label><select class="form-select" name="day_of_week">@foreach(['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as $value=>$label)<option value="{{ $value }}" @selected((string)old('day_of_week',$schedule?->day_of_week ?? 0)===(string)$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-4" data-monthly><label class="form-label">Day of month</label><input class="form-control" type="number" name="day_of_month" min="1" max="31" value="{{ old('day_of_month',$schedule?->day_of_month ?? 1) }}"></div>
    <div class="col-md-4"><label class="form-label">Retention method</label><select class="form-select" name="retention_type"><option value="count" @selected(old('retention_type',$schedule?->retention_type ?? 'count')==='count')>Number of backups</option><option value="days" @selected(old('retention_type',$schedule?->retention_type)==='days')>Age in days</option></select></div>
    <div class="col-md-4"><label class="form-label">Retention value</label><input class="form-control" type="number" name="retention_value" min="1" max="3650" required value="{{ old('retention_value',$schedule?->retention_value ?? 7) }}"></div>
    <div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="enabled" value="0"><input class="form-check-input" type="checkbox" name="enabled" value="1" id="enabled-{{ $prefix }}" @checked(old('enabled',$schedule?->enabled ?? true))><label class="form-check-label" for="enabled-{{ $prefix }}">Schedule enabled</label></div></div>
    <div class="col-12"><div class="alert alert-info mb-0 py-2 small"><i class="fa-solid fa-circle-info me-2"></i>For monthly schedules, days beyond a month’s length run on that month’s final day.</div></div>
</div>
